export const ADD_PROFILEDATA = 'add_profiledata'
export const ADD_DIRECPROFILEDATA = 'add_direcProfiledata'
export const SHOW_PIC = 'show_pic'
export const FIREBASE_DATA = 'get_data'
export const UPDATE_FIREBASE_DATA = 'update_data'
